### ISSUE TITLE
18f Guides Consolidation - Accessibility

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#546]
## Summary

Look at the pathways available to consolidate the current 18F Guides, specifically Accessibility. 

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [x] migrate existing pages into 18f.gsa.gov page heirarchy
- [x] write up steps taken to migrate guide (frontmatter updates, css updates, inclusion of js, any formatting changes)
- [x] denote any changes required to the original site
  - Breadcrumb component was updated to render appropriate names at different levels. This component is not used elsewhere on 18f.gsa.gov and could benefit from some refactoring away from agency/ sub-agency naming conventions.
- [x] track time spent (6hrs as of 8/11/2022)
- [x] deploy site to a source that is sharable to the team (gh pages, cloud.gov, etc) >>> https://guides-migration-terrific-quokka-xe.app.cloud.gov/guides/accessibility/
- [x] review with team
- [x] present to 18f

### Prerequisites

- cloud.gov account
- cloudfoundry cli
- rvm
- node

## Migration Steps

- create new folder under pages/guides/ with the guide name
- update frontmatter
  - update permalink value to: `/guides/{name}/pagetitle`
  - change 'description' to 'lead'
  - remove 'page_title'
  - remove 'sidenav'
  - remove 'layout'
  - add 'agency' and enter the page title 
  - add 'subnav_title' and use same name as agency
  - add 'subnav_items' and child records which corresponds to <h2> headers on page, example below
```yml
subnav_items:
  - text: Testing
    permalink: /guides/accessibility/iframes/#testing
  - text: Examples
    permalink: /guides/accessibility/iframes/#examples
```
- update `_config.yml` to include defaults for new directory. This helps set frontmatter attributes for the directory and also informs the breadcrumb component (see items below 'breadcrumb: true') Example for accessibility pages below:

```yml
- 
  scope:
    path: "pages/guides/accessibility/*"
  values:
    include_subnav: true
    breadcrumb: true
    parent_title: Guides
    parent_permalink: /guides/
    sub_parent_title: Accessibility
    sub_parent_permalink: /guides/accessibility/
    sub_parent_agency: Accessibility
```

- copy js files
  - create new folder under `assets/js/guides` with the name of the new guide
  - place any relevant js files into it
- copy css/scss
  - Review `_sass` folder for any page-specific css files or files that exist outside of the typical USWDS set
  - migrate files to `_sass` folder

- deploy to cloud.gov
`cf push {project name} --random-route -f manifest.yml -b https://github.com/cloudfoundry/staticfile-buildpack`
